[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kdtree = "0.7.0"
macroquad = "0.4.4"
rand = "0.8.5"
reverse = "0.2.2"
talos = "0.1.0"
